apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  virtualhost:
    fqdn: longhorn.idc.craigcloud.io
  routes:
  - conditions:
    - prefix: /
    services:
    - name: longhorn-frontend
      port: 80
