---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./dialtone/contour
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dialtone
  namespace: flux-system
spec:
  dependsOn:
  - name: ingress
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./dialtone
  prune: true
