---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: heimdall
  namespace: heimdall
spec:
  virtualhost:
    fqdn: dashboard.idc.craigcloud.io
  routes:
  - conditions:
    - prefix: /
    services:
    - name: heimdall
      port: 80
