---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter-ft
  namespace: jupyter-ft
spec:
  virtualhost:
    fqdn: datascience.idc.craigcloud.io
  routes:
  - conditions:
    - prefix: /
    services:
    - name: jupyter-ft-fine-tune-jupyter
      port: 8888
