---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: prometheus
spec:
  virtualhost:
    fqdn: grafana.idc.craigcloud.io
  routes:
  - conditions:
    - prefix: /
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
