apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyter-ft
  namespace: jupyter-ft
spec:
  releaseName: jupyter-ft
  chart:
    spec:
      chart: fine-tune-jupyter
      sourceRef:
        kind: HelmRepository
        name: nctiggy
        namespace: flux-system
      version: "0.0.3"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v0.0.9
    persistence:
      data:
        enabled: true
        size: 32Gi
        retain: true
        accessMode: ReadWriteOnce
